### ISSUE TITLE
Is it possible to use the Babel-acorn for this?

### ISSUE THREAD

**Issue by nmn** [KenPowers/falafelify#3]
With React and JSX, Acorn and Esprima break down. But Babel already has an extended version of Acorn that understands all the new syntax. Is it possible to use that version of acorn with Falafelify?

**Comment by knpwrs** [comment]
Whatever is possible with [falafel](https://github.com/substack/node-falafel) is possible here. This tool just builds around falafel and doesn't access any of the internals.
