### ISSUE TITLE
No way to filter for valid files

### ISSUE THREAD

**Issue by tivac** [KenPowers/falafelify#4]
Falafelify is an awesome idea, but I've run into a problem.

Tools like [coffeeify](https://github.com/jnordberg/coffeeify/blob/master/index.js#L75) have an internal check on the file extension so they don't try to run on types of files they don't need to care about. I don't see any sort of filtering functionality like that in falafelify.

I ran into this while trying to build a falafelify-powered transform that also plays nicely with [css-modulesify](https://www.npmjs.com/package/css-modulesify). Since there are CSS files floating around acorn unsurprisingly explodes on the invalid JS contained within.

Any ideas? I'd be happy to send a PR if you have a preferred solution.

**Comment by knpwrs** [comment]
I wouldn't be opposed to a pull request for this functionality, but I think the extensions should be overridable through the options parameter.

**Comment by tivac** [comment]
Sorry, I think you should have to opt into the filtering. Default behavior would remain as-is :)

Something like this-ish?

``` js
falafelify({ exts : [ "js" ] }, fn);
```

**Comment by knpwrs** [comment]
Go for it.

**Comment by tivac** [comment]
I ended up just using `falafel` directly.
