### ISSUE TITLE
Maxmimum call stack exceeded

### ISSUE THREAD

**Issue by xkr47** [KenPowers/falafelify#5]
I encountered the error in the headline with my js files. I solved/worked around the issue by reimplementing falafelify functionality myself, excluding the parallel async part - I guess those done() calls started processing new tasks recursively, consuming up the stack quickly.

If my theory regarding recursive done() calls is true then the fix maybe should go into the async library. But for me it's ok without the parallellism so I'm not currently investigating this further. A workaround could perhaps be a user option to disable the parallellism?

Thanks for showing the path :)

**Comment by knpwrs** [comment]
I don't really know what the problem you are reporting is. In any case, I've started recommending that people start writing babel transforms. I may be deprecating this transform soon.
